Fiorello/Fiorello/Models/About.cs
namespace Fiorello.Models
{
    public class About :BaseEntity
    {
        public string ? Heading { get; set; }
        public string ? Description { get; set; }

        public string ? Icon { get; set; }

        
    }
}

Fiorello/Fiorello/Models/BaseEntity.cs
namespace Fiorello.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public bool SoftDeleted { get; set; } = false;
        public DateTime CreatedDate { get; set; } = DateTime.Now;

    }
}

Fiorello/Fiorello/Models/Blog.cs
namespace Fiorello.Models
{
    public class Blog:BaseEntity
    {

        public string ? BlogImage { get; set; }
        public string ? Title { get; set; }
        public string ? Description { get; set; }

        

    }
}

Fiorello/Fiorello/Models/BlogDetail.cs
namespace Fiorello.Models
{
    public class BlogDetail :BaseEntity
    {
        public string ? Title { get; set; }
        public string ? Description { get; set; }
    }
}

Fiorello/Fiorello/Models/Category.cs
namespace Fiorello.Models
{
    public class Category :BaseEntity
    {
        public string ? Name { get; set; }

        public ICollection<Product> ? Products { get; set; }
    }
}

Fiorello/Fiorello/Models/Expert.cs
namespace Fiorello.Models
{
    public class Expert :BaseEntity
    {
        public string ? ExpertImage { get; set; }
        public string ? FullName { get; set; }
        public string ? Position { get; set; }
    }
}

Fiorello/Fiorello/Models/Instagram.cs
namespace Fiorello.Models
{
    public class Instagram :BaseEntity
    {
        public string ? InstagramImage { get; set; }
    }
}

Fiorello/Fiorello/Models/Product.cs
namespace Fiorello.Models
{
    public class Product :BaseEntity
    {
        public string ? Name { get; set; }
        public decimal Price { get; set; }
        public string ? Description { get; set; }
        public int CategoryId { get; set; }
        public Category ? Category { get; set; }       
        public ICollection<ProductImage> ? Images { get; set; }
    }
}

Fiorello/Fiorello/Models/ProductImage.cs
namespace Fiorello.Models
{
    public class ProductImage:BaseEntity
    {
        public string ? Image { get; set; }
        public int ProductId { get; set; }
        public Product ? Product { get; set; }
        public bool IsMain { get; set; }
    }
}

Fiorello/Fiorello/Models/Slider.cs
namespace Fiorello.Models
{
    public class Slider:BaseEntity
    {
        public string ? SliderImage { get; set; }
    }
}

Fiorello/Fiorello/Models/SliderInfo.cs
namespace Fiorello.Models
{
    public class SliderInfo :BaseEntity
    {
        public string ? Title { get; set; }
        public string ? Description { get; set; }
        public string ? SignImage { get; set; }
    }
}

Fiorello/Fiorello/Models/Start.cs
namespace Fiorello.Models
{
    public class Start :BaseEntity
    {

        public string ? StartImage { get; set; }
        public string ? Comment { get; set; }

        public string ? FullName { get; set; }

        public string ? Position { get; set; }
    }
}

Fiorello/Fiorello/ViewModels/BlogVM.cs
namespace Fiorello.ViewModels
{
    public class BlogVM
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }

        public string ? Image { get; set; }

    }
}

Fiorello/Fiorello/ViewModels/HomeVM.cs
using Fiorello.Models;

namespace Fiorello.ViewModels
{
    public class HomeVM
    {
        public IEnumerable<Slider> ? Sliders { get; set; }
        public SliderInfo ? SliderInfo { get; set; }

        public IEnumerable<Blog>? Blogs { get; set; }

        public BlogDetail ? BlogDetail { get; set; }

        public IEnumerable<Category>? Categories { get; set; }

        public IEnumerable<Product>? Products { get; set; }

        public About ? About { get; set; }

        public IEnumerable<Expert>? Experts { get; set; }
        public IEnumerable<Start>? Starts { get; set; }

        public IEnumerable<Instagram>? Instagram { get; set; }

    }
}

Fiorello/Fiorello/ViewModels/ProductDetailVM.cs
using Fiorello.Models;

namespace Fiorello.ViewModels
{
    public class ProductDetailVM
    {
        public int Id { get; set; }
        public string ? Name { get; set; }
        public string ? CategoryName { get; set; }
        public List<ProductImage> ? Images { get; set; }
        public decimal Price { get; set; }
        public string ? Description { get; set; }
    }
}

Fiorello/Fiorello/Controllers/BlogController.cs
using Fiorello.Data;
using Fiorello.Models;
using Fiorello.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiorello.Controllers
{
    public class BlogController : Controller
    {


        private readonly AppDbContext _context;

        public BlogController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(int? id)
        {

            if (id is null) return BadRequest();

            Blog blog = await _context.Blogs.Where(m => !m.SoftDeleted).FirstOrDefaultAsync(x => x.Id == id);

            if (blog is null) return NotFound();

            BlogVM blogVm = new()
            {
                Id = blog.Id,
                Name = blog.Title,
                Description = blog.Description,
                Image=blog.BlogImage              

            };

            return View(blogVm);
        }
    }
}

Fiorello/Fiorello/Controllers/HomeController.cs
using Fiorello.Data;
using Fiorello.Models;
using Fiorello.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Fiorello.Controllers
{
    public class HomeController : Controller
    {

        private readonly AppDbContext _context;

        public HomeController(AppDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            IEnumerable<Slider> sliders = await _context.Sliders.Where(m => !m.SoftDeleted).ToListAsync();
            SliderInfo sliderInfo = await _context.SlidersInfo.Where(m=>!m.SoftDeleted).FirstOrDefaultAsync();
            IEnumerable<Blog> blog = await _context.Blogs.Where(m => !m.SoftDeleted).Take(3).ToArrayAsync();
            BlogDetail blogDetail = await _context.BlogsDetails.Where(m => !m.SoftDeleted).FirstOrDefaultAsync();
            IEnumerable<Category> categories = await _context.Categories.Where(m => !m.SoftDeleted).ToArrayAsync();
            IEnumerable<Product> products=await _context.Products.Include(m=>m.Images).Where(m => !m.SoftDeleted).ToArrayAsync();
            About about = await _context.Abouts.Where(m => !m.SoftDeleted).FirstOrDefaultAsync();
            IEnumerable<Expert>  experts= await _context.Experts.Where(m => !m.SoftDeleted).Take(4).ToArrayAsync();
            IEnumerable<Start> starts = await _context.Starts.Where(m => !m.SoftDeleted).Take(2).ToArrayAsync();
            IEnumerable<Instagram> instagrams = await _context.Instagrams.Where(m => !m.SoftDeleted).ToArrayAsync();

            HomeVM homeVM = new() 
            { 
            
                SliderInfo = sliderInfo,
                Sliders = sliders,
                Blogs= blog,
                BlogDetail = blogDetail,
                Categories = categories,
                Products = products,
                About = about,
                Experts = experts,
                Starts = starts,
                Instagram = instagrams
                
            
            };

            return View(homeVM);
        }

       
    }
}

Fiorello/Fiorello/Controllers/ProductController.cs
using Fiorello.Data;
using Fiorello.Models;
using Fiorello.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Fiorello.Controllers
{
    public class ProductController : Controller
    {

        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int? id)
        {

            if (id is null) return BadRequest();

            Product product = await _context.Products.Include(m => m.Images).Include(m=>m.Category).Where(m => !m.SoftDeleted).FirstOrDefaultAsync(x => x.Id == id);
            
            if (product is null) return NotFound();

            ProductDetailVM productDetailVM = new()
            {
                Id = product.Id,
                Name = product.Name,
                CategoryName=product.Category.Name,
                Price = product.Price,  
                Description = product.Description,
                Images=product.Images.ToList()

            };

            return View(productDetailVM);
        }

    }
}

Fiorello/Fiorello/Views/Blog/Index.cshtml
@model BlogVM

@{
    ViewData["Title"] = "Index";
}

<style>
    body {
        background-color: gray
    }

    .card {
        border: none
    }

    .product {
        
        margin-right: 100px;
        background-color: #eee
    }

    .brand {
        font-size: 13px
    }

    .act-price {
        color: red;
        font-weight: 700
    }

    .dis-price {
        text-decoration: line-through
    }

    .about {
        font-size: 14px
    }

    .color {
        margin-bottom: 10px
    }


    a {
        text-decoration: none;
        outline: none;
        color: black;
    }

        a:hover {
            color: black;
        }

    label.radio {
        cursor: pointer
    }

        label.radio input {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none
        }

        label.radio span {
            padding: 2px 9px;
            border: 2px solid #ff0000;
            display: inline-block;
            color: #ff0000;
            border-radius: 3px;
            text-transform: uppercase
        }

        label.radio input:checked + span {
            border-color: #ff0000;
            background-color: #ff0000;
            color: #fff
        }

    .btn-danger {
        background-color: #ff0000 !important;
        border-color: #ff0000 !important
    }

        .btn-danger:hover {
            background-color: #da0606 !important;
            border-color: #da0606 !important
        }

        .btn-danger:focus {
            box-shadow: none
        }

    .cart i {
        margin-right: 10px
    }
</style>



<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> <img id="main-image" src="~/img/@Model.Image" width="250" /> </div>
                          
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <a asp-controller="Home" asp-action="Index">
                                    <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1">Back</span> 
                                        </div>
                                </a>

                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@Model.Name</span>
                                <h5 class="text-uppercase">@Model.Description</h5>
                                
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Fiorello/Fiorello/Views/Home/Index.cshtml
@model HomeVM

@{
    ViewData["Title"] = "Home Page";
}

  <!-- MAIN START -->

    <main>

        <!-- SLIDER START -->

        <section id="slider">
            <div class="owl-carousel slider">
                @foreach (var slider in Model.Sliders)
            {
                <div> <img src="~/img/@slider.SliderImage" alt=""> </div>
            }               
             
            </div>
            <div class="container context pl-lg-5 ml-lg-3">
                <div class="row">
                    <div class="col-lg-5">
                        <div class="text">
                           @Html.Raw(Model.SliderInfo.Title)
                            <p class="text-black-50 d-none d-sm-block">@Model.SliderInfo.Description</p>
                        </div>
                        <div class="img">
                            <img src="~/img/@Model.SliderInfo.SignImage" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SLIDER END -->

        <!-- PRODUCTS START -->

        <section id="products">
            <div class="container">
                <div class="row pt-5">
                    <div class="col-12 d-flex justify-content-between">
                        <ul class="category-mobile d-md-none list-unstyled">
                            <li>
                                <a href="" class="categories mr-2">Categories</a>
                                <i class="fas fa-caret-down"></i>
                                <ul class="category list-unstyled" style="display: none;">
                                    <li><a href="" data-id="all">All</a></li>
                                    <li><a href="" data-id="popular">Popular</a></li>
                                    <li><a href="" data-id="winter">Winter</a></li>
                                    <li><a href="" data-id="various">Various</a></li>
                                    <li><a href="" data-id="exotic">Exotic</a></li>
                                    <li><a href="" data-id="green">Greens</a></li>
                                    <li><a href="" data-id="cactuse">Cactuses</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="category d-none d-md-flex list-unstyled">
                            <li><a href="" data-id="all">All</a></li>
                            @foreach (var category in Model.Categories)
                        {
                            <li><a href="" data-id=@category.Id>@category.Name</a></li>
                        }
                            
                            
                        </ul>
                        <ul class="list-unstyled">
                            <li>
                                <a href="" class="mr-2">Filter</a>
                                <i class="fas fa-caret-down"></i>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">

                    @foreach (var product in Model.Products)
                {
                      <div class="col-sm-6 col-md-4 col-lg-3 mt-3">
                        <div class="product-item text-center" data-id=@product.CategoryId>
                            <div class="img">
                                <a asp-controller="Product" asp-action="Index" asp-route-id="@product.Id">
                                    <img src="~/img/@product.Images?.Where(m=>m.IsMain).FirstOrDefault().Image" class="img-fluid" alt="">
                                </a>
                            </div>
                            <div class="title mt-3">
                                <h6>@product.Name</h6>
                            </div>
                            <div class="price">
                                <span class="text-black-50">Add to cart</span>
                                <span class="text-black-50">$@product.Price</span>
                            </div>
                        </div>
                    </div>
                }
                  
                    
                </div>
            </div>
        </section>

        <!-- PRODUCTS END -->

        <!-- ABOUT START -->

        <section id="about">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-lg-6">
                        <div class="img">
                            <img src="~/img/h3-video-img.jpg" class="img-fluid" alt="">
                            <div
                                class="player position-absolute rounded-circle d-flex align-items-center justify-content-center">
                                <i class="fas fa-play fa-lg"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="about-text mt-5 mt-lg-0 px-lg-5">
                            @Html.Raw(Model.About.Heading)
                            <p class="py-3">@Model.About.Description</p>
                            <ul class="list-unstyled">
                                <li class="mt-3"><img src="~/img/@Model.About.Icon" class="mr-2" alt=""> Hand picked just
                                    for you.</li class="mt-3">
                                <li class="mt-3"><img src="~/img/@Model.About.Icon" class="mr-2" alt=""> Unique flower
                                    arrangements</li>
                                <li class="mt-3"><img src="~/img/@Model.About.Icon" class="mr-2" alt=""> Best way to say
                                    you care.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ABOUT END -->

        <!-- EXPERTS START -->

        <section id="experts">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>Flower Experts</h1>
                            <p class="text-black-50">A perfect blend of creativity, energy, communication, happiness and
                                love. Let us arrange
                                a smile for you.</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">

                
                    @foreach (var expert in Model.Experts)
                {
                     <div class="col-md-6 col-lg-3">
                        <div class="item text-center">
                            <div class="img">
                                <img src="~/img/@expert.ExpertImage" class="img-fluid rounded-circle" alt="">
                            </div>
                            <div class="text mt-3">
                                <h6>@expert.FullName</h6>
                                <p class="text-black-50">@expert.Position</p>
                            </div>
                        </div>
                    </div>
                }                 
                   
                </div>
            </div>
        </section>

        <!-- EXPERTS END -->

        <!-- SUBSCRIBE START -->

        <section id="subscribe">
            <div class="container py-5">
                <div class="row py-5">
                    <div class="col-12">
                        <div class="content text-center py-5">
                            <h3>Join The Colorful Bunch!</h3>
                            <div class="form-group d-flex justify-content-center flex-wrap mt-5">
                                <input type="email" placeholder="Email Address" class="form-control-lg rounded-0">
                                <button class="btn btn-danger btn-lg rounded-0 px-5 mt-3 mt-sm-0">Subscribe</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SUBSCRIBE END -->

        <!-- BLOG START -->

        <section id="blog">
            <div class="container">
                <div class="row py-5">
                    <div class="offset-lg-3 col-lg-6">
                        <div class="section-title">
                            <h1>@Model.BlogDetail.Title</h1>
                            <p class="text-black-50">@Model.BlogDetail.Description</p>
                        </div>
                    </div>
                </div>
                <div class="row pb-5">

                    @foreach (var blog in Model.Blogs)
                {
                     <div class="col-md-6 col-lg-4">
                        <div class="item">                           
                            <div class="img position-relative">
                                <a asp-controller="Blog" asp-action="Index" asp-route-id="@blog.Id">
                                    <img src="~/img/@blog.BlogImage" class="img-fluid" alt="">
                                </a>                                
                                <div class="date rounded bg-light position-absolute py-1 px-2">
                                    <span>@blog.CreatedDate.ToString("MM.dd.yyyy")</span>
                                </div>
                            </div>
                            <div class="text mt-3 text-center px-5">
                                <h5>@blog.Title</h5>
                                <p class="text-black-50">@blog.Description</p>
                            </div>
                        </div>
                    </div>
                }
                   
                   
                </div>
            </div>
        </section>

        <!-- BLOG END -->

        <!-- SAY START -->

        <section id="say">
            <div class="container">
                <div class="row py-5 justify-content-center">
                    <div class="col-md-8 col-xl-6">
                        <div class="owl-carousel say">
                            @foreach (var start in Model.Starts)
                        {
                                                        <div>
                                <div class="item text-center">
                                    <div class="img d-flex justify-content-center">
                                        <img src="~/img/@start.StartImage" alt="">
                                    </div>
                                    <div class="text text-muted pt-3 pb-5">
                                        <i>@start.Comment</i>
                                    </div>
                                    <div class="author">
                                        <h6>@start.FullName</h6>
                                        <p class="text-black-50">@start.Position</p>
                                    </div>
                                </div>
                            </div>
                            
                        }

                          
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- SAY END -->

        <!-- INSTAGRAM START -->

        <section id="instagram">
            <div class="owl-carousel instagram">

                @foreach (var inst in Model.Instagram)
            {
                <div><img src="~/img/@inst.InstagramImage" class="img-fluid" alt=""></div>                
            }
                
                
            </div>
            <div class="hastag bg-light text-muted py-2 px-3">
                #FIORELLO
            </div>
        </section>

        <!-- INSTAGRAM END -->

    </main>

    <!-- MAIN END -->

Fiorello/Fiorello/Views/Product/Index.cshtml
@model ProductDetailVM

@{
    ViewData["Title"] = "Index";
}


<style>
    body {
        background-color: gray
    }

    .card {
        border: none
    }

    .product {
        margin-top:100px;
        margin-right:100px;
        background-color: #eee
    }

    .brand {
        font-size: 13px
    }

    .act-price {
        color: red;
        font-weight: 700
    }

    .dis-price {
        text-decoration: line-through
    }

    .about {
        font-size: 14px
    }

    .color {
        margin-bottom: 10px
    }


    a{
        text-decoration:none;
        outline:none;
        color:black;
    }

    a:hover{
        color:black;

    }

    label.radio {
        cursor: pointer
    }

        label.radio input {
            position: absolute;
            top: 0;
            left: 0;
            visibility: hidden;
            pointer-events: none
        }

        label.radio span {
            padding: 2px 9px;
            border: 2px solid #ff0000;
            display: inline-block;
            color: #ff0000;
            border-radius: 3px;
            text-transform: uppercase
        }

        label.radio input:checked + span {
            border-color: #ff0000;
            background-color: #ff0000;
            color: #fff
        }

    .btn-danger {
        background-color: #ff0000 !important;
        border-color: #ff0000 !important
    }

        .btn-danger:hover {
            background-color: #da0606 !important;
            border-color: #da0606 !important
        }

        .btn-danger:focus {
            box-shadow: none
        }

    .cart i {
        margin-right: 10px
    }
</style>



<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="row">
                    <div class="col-md-6">
                        <div class="images p-3">
                            <div class="text-center p-4"> <img id="main-image" src="~/img/@Model.Images.Where(m=>m.IsMain).FirstOrDefault().Image" width="250" /> </div>
                            <div class="thumbnail text-center">
                                @foreach (var item in Model.Images)
                                {
                                    <img onclick="change_image(this)" src="~/img/@item.Image" width="70">
                                }                               
                                 
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="product p-4">
                            <div class="d-flex justify-content-between align-items-center">
                                <a asp-controller="Home" asp-action="Index">
                                    <div class="d-flex align-items-center"> <i class="fa fa-long-arrow-left"></i> <span class="ml-1">Back</span> </div> <i class="fa fa-shopping-cart text-muted"></i>
                                </a>
                                
                            </div>
                            <div class="mt-4 mb-3">
                                <span class="text-uppercase text-muted brand">@Model.CategoryName</span>
                                <h5 class="text-uppercase">@Model.Name</h5>
                                <div class="price d-flex flex-row align-items-center">                                    
                                    <div class="ml-2"><small class="dis-price">$@Model.Price.ToString("0.#####")</small></div>
                                </div>
                            </div>
                            <p class="about">@Model.Description</p>                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>

    function change_image(image) {

        var container = document.getElementById("main-image");

        container.src = image.src;
    }

    document.addEventListener("DOMContentLoaded", function (event) {

    });
</script>